# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HTodo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HTodo
  pod 'RealmSwift', '~>10'

  target 'HTodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HTodoUITests' do
    # Pods for testing
  end

end
